version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: seu_usuario
      POSTGRES_PASSWORD: sua_senha_forte
      POSTGRES_DB: seu_banco
    ports:
      - "5432:5432"
