version: '3.8'
services:
  db:
    image: postgres:15
    env_file: .env.example
    volumes: ['./data:/var/lib/postgresql/data']
  web:
    build: .
    env_file: .env.example
    ports:
      - "8000:8000"
    depends_on:
      - db
